#!/usr/bin/env bash
# =============================================================================
# setup-client.sh
#
# Automated setup for a Snapcast CLIENT on Raspberry Pi Zero with
# HiFiBerry DAC+ Zero 1.x hat.
#
# What this script does:
#   1. Updates the system
#   2. Enables the HiFiBerry DAC+ Zero device-tree overlay
#   3. Disables the conflicting built-in audio driver
#   4. Creates /etc/asound.conf for the DAC
#   5. Installs snapclient
#   6. Configures snapclient to connect to the server and output via the DAC
#   7. Disables WiFi power management (FIXES periodic disconnect / cut-out)
#   8. Tunes TCP keep-alive parameters
#   9. Enables unattended-upgrades
#  10. Installs a watchdog service that auto-restarts snapclient
#  11. Enables and starts services
#  12. Prints a post-setup summary and reboot reminder
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/tipbr/snapcast-instructions-scripts/main/scripts/setup-client.sh | sudo bash
#   — or —
#   sudo bash setup-client.sh
#
# Tested on: Raspberry Pi OS Lite (Bookworm / Bullseye), Raspberry Pi Zero W
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — edit these if your setup differs
# ---------------------------------------------------------------------------
SNAPCAST_VERSION="0.27.0"
SERVER_IP="192.168.0.230"

# ALSA card name for HiFiBerry DAC+ Zero after overlay is loaded.
# This matches the overlay name; verify with 'aplay -l' after first reboot.
DAC_CARD="sndrpihifiberry"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { echo "[setup-client] $*"; }
die()  { echo "[setup-client] ERROR: $*" >&2; exit 1; }

require_root() {
    [ "$(id -u)" -eq 0 ] || die "This script must be run as root (use sudo)."
}

detect_arch() {
    local arch
    arch=$(dpkg --print-architecture)
    case "$arch" in
        armhf|arm64|amd64) echo "$arch" ;;
        # Pi Zero (ARMv6) reports armhf in Raspberry Pi OS
        *) die "Unsupported architecture: $arch" ;;
    esac
}

# Determine the correct boot config file
boot_config() {
    if [ -f /boot/firmware/config.txt ]; then
        echo /boot/firmware/config.txt
    else
        echo /boot/config.txt
    fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
require_root

log "=== Snapcast Client Setup starting ==="
log "Server: ${SERVER_IP}"

# --- 1. System update -------------------------------------------------------
log "Updating package lists and upgrading installed packages..."
apt-get update -y
apt-get full-upgrade -y
apt-get install -y curl wget unattended-upgrades wireless-tools

# --- 2. Enable HiFiBerry DAC+ Zero overlay ----------------------------------
CONFIG_FILE=$(boot_config)
log "Configuring HiFiBerry DAC+ Zero overlay in ${CONFIG_FILE}..."

# Disable built-in audio (it conflicts with the HiFiBerry driver)
if grep -q "^dtparam=audio=on" "$CONFIG_FILE"; then
    sed -i 's/^dtparam=audio=on/#dtparam=audio=on  # disabled — using HiFiBerry DAC/' "$CONFIG_FILE"
    log "Built-in audio disabled (conflicts with HiFiBerry)."
fi

# Remove any existing hifiberry-dac line before adding a clean one
sed -i '/^dtoverlay=hifiberry-dac/d' "$CONFIG_FILE"

echo "" >> "$CONFIG_FILE"
echo "# HiFiBerry DAC+ Zero 1.x" >> "$CONFIG_FILE"
echo "dtoverlay=hifiberry-dac" >> "$CONFIG_FILE"
log "hifiberry-dac overlay added to ${CONFIG_FILE}."

# --- 3. Configure ALSA -------------------------------------------------------
log "Writing /etc/asound.conf for HiFiBerry DAC..."

cat > /etc/asound.conf <<EOF
# ALSA configuration — HiFiBerry DAC+ Zero
# Generated by setup-client.sh

pcm.!default {
    type hw
    card ${DAC_CARD}
}

ctl.!default {
    type hw
    card ${DAC_CARD}
}
EOF

# --- 4. Install snapclient --------------------------------------------------
ARCH=$(detect_arch)
log "Detected architecture: $ARCH"
log "Installing Snapcast client ${SNAPCAST_VERSION}..."

BASE_URL="https://github.com/badaix/snapcast/releases/download/v${SNAPCAST_VERSION}"
CLIENT_DEB="snapclient_${SNAPCAST_VERSION}-1_${ARCH}.deb"

wget -q "${BASE_URL}/${CLIENT_DEB}" -O "/tmp/${CLIENT_DEB}"
apt-get install -y "/tmp/${CLIENT_DEB}"
rm -f "/tmp/${CLIENT_DEB}"
log "snapclient installed."

# --- 5. Configure snapclient ------------------------------------------------
log "Configuring snapclient..."

[ -f /etc/default/snapclient ] && cp /etc/default/snapclient /etc/default/snapclient.bak

cat > /etc/default/snapclient <<EOF
# snapclient configuration
# Generated by setup-client.sh

START_SNAPCLIENT=true
SNAPCLIENT_OPTS="--host ${SERVER_IP} --soundcard hw:${DAC_CARD} --latency 0"
EOF

# --- 6. Disable WiFi power management ----------------------------------------
#
# This is the PRIMARY fix for the periodic disconnect / cut-out issue.
# The Linux WiFi driver puts the interface into a low-power sleep state by
# default, which drops the TCP connection to snapserver.
#
log "Disabling WiFi power management (fixes periodic disconnects)..."

# NetworkManager (Bookworm default)
if systemctl is-active --quiet NetworkManager 2>/dev/null; then
    mkdir -p /etc/NetworkManager/conf.d
    cat > /etc/NetworkManager/conf.d/99-disable-wifi-powersave.conf <<EOF
# Disable WiFi power saving to prevent Snapcast disconnects
[connection]
wifi.powersave = 2
EOF
    log "WiFi power save disabled via NetworkManager config."
fi

# Fallback: dhcpcd / wpa_supplicant systems (Bullseye)
if [ -f /etc/rc.local ]; then
    if ! grep -q "iwconfig wlan0 power off" /etc/rc.local; then
        sed -i 's/^exit 0/\/sbin\/iwconfig wlan0 power off 2>\/dev\/null || true\n\nexit 0/' /etc/rc.local
        log "WiFi power off added to /etc/rc.local."
    fi
fi

# Apply immediately (best-effort)
/sbin/iwconfig wlan0 power off 2>/dev/null || true

# --- 7. TCP keep-alive tuning ------------------------------------------------
log "Tuning TCP keep-alive parameters..."

cat > /etc/sysctl.d/99-tcp-keepalive.conf <<EOF
# TCP keep-alive tuning for Snapcast stability
net.ipv4.tcp_keepalive_time   = 60
net.ipv4.tcp_keepalive_intvl  = 10
net.ipv4.tcp_keepalive_probes = 6
EOF

sysctl -p /etc/sysctl.d/99-tcp-keepalive.conf

# --- 8. Automatic security updates ------------------------------------------
log "Enabling unattended-upgrades..."

cat > /etc/apt/apt.conf.d/50unattended-upgrades-snapcast <<EOF
Unattended-Upgrade::Automatic-Reboot "false";
Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";
Unattended-Upgrade::Remove-Unused-Dependencies "true";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades-snapcast <<EOF
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

systemctl enable --now unattended-upgrades

# --- 9. Watchdog service -----------------------------------------------------
log "Installing Snapcast watchdog service..."

cat > /usr/local/bin/snapcast-watchdog.sh <<'WATCHDOG'
#!/usr/bin/env bash
# Snapcast watchdog — restarts snapclient if it stops.
SERVICES=("snapclient")

while true; do
    for svc in "${SERVICES[@]}"; do
        if systemctl list-unit-files --quiet "${svc}.service" 2>/dev/null; then
            if ! systemctl is-active --quiet "${svc}"; then
                echo "$(date '+%Y-%m-%d %H:%M:%S') [watchdog] ${svc} is not active — restarting"
                systemctl restart "${svc}" || true
            fi
        fi
    done
    sleep 30
done
WATCHDOG

chmod +x /usr/local/bin/snapcast-watchdog.sh

cat > /etc/systemd/system/snapcast-watchdog.service <<EOF
[Unit]
Description=Snapcast watchdog — restart failed snapclient
After=network.target snapclient.service

[Service]
Type=simple
ExecStart=/usr/local/bin/snapcast-watchdog.sh
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# Harden snapclient restart policy
mkdir -p /etc/systemd/system/snapclient.service.d
cat > /etc/systemd/system/snapclient.service.d/restart.conf <<EOF
[Service]
Restart=on-failure
RestartSec=5s
EOF

# --- 10. Enable services -----------------------------------------------------
#
# NOTE: snapclient needs the DAC to be present (loaded via device-tree overlay)
# before it can output audio.  The overlay only takes effect after a reboot.
# We enable the service now so it starts automatically on the next boot.
#
log "Enabling services (will start properly after reboot)..."

systemctl daemon-reload
systemctl enable snapclient snapcast-watchdog

# Attempt to start immediately — this will likely fail until the reboot
# applies the DAC overlay, but the service will come up correctly after reboot.
systemctl restart snapclient 2>/dev/null || log "(snapclient start deferred — DAC not yet available; will start after reboot)"
systemctl start  snapcast-watchdog 2>/dev/null || true

# --- Summary ----------------------------------------------------------------
log ""
log "=== Setup complete! ==="
log ""
log "IMPORTANT: A reboot is required to activate the HiFiBerry DAC+ Zero"
log "device-tree overlay.  Run:"
log "  sudo reboot"
log ""
log "After rebooting, verify the DAC is detected:"
log "  aplay -l   (should list 'sndrpihifiberry')"
log ""
log "Verify snapclient is running and connected:"
log "  systemctl status snapclient"
log ""
log "If the DAC card name shown by 'aplay -l' differs from '${DAC_CARD}',"
log "update /etc/default/snapclient and /etc/asound.conf accordingly."
log ""
log "Check WiFi power management is off (critical for stability):"
log "  iwconfig wlan0   (should show 'Power Management:off')"
